NuMFor: mtrandom Module Reference
mtrandom Module Reference
Random generator for uniform distributions.
Data Types
interface random
returns one or several numbers
random(state, r)
type rng_state
rng_state holds the state of the generator
interface seed
initializes the generator. Use it as
seed(key, state)
Functions/Subroutines
integer(i64) function, public rng_rand64 (state)
Obtain the next 64-bit (orig said 32??) integer in the pseudo-random sequence.
integer(4) function, public rng_rand (state)
Obtain the next 32-bit integer in the pseudo-random sequence.
integer(4) function, public rng_rand_range (state, lo, hi)
Obtain a pseudorandom integer in the range [lo,hi].
real(dp) function, public rng_rand_real1 (state)
Obtain a pseudorandom real number in the range [0,1],.
real(dp) function, public rng_rand_real2 (state)
Obtain a pseudorandom real number in the range [0,1)
real(dp) function, public rng_rand_real3 (state)
Obtain a pseudorandom real number in the range (0,1)
Detailed Description
Random generator for uniform distributions.
Remarks
they try to have only one (common) interface
random returns random numbers
random(state, r)
state is a random_state type variable
r is either a real scalar or a 1D, 2D or 3D array
seed Seed the generator
seed(key, state)
key is, if present, either an integer scalar or 1D array
state is a random_state type variable
Data Type Documentation
mtrandom::rng_state
type mtrandom::rng_state
rng_state holds the state of the generator
Function/Subroutine Documentation
rng_rand()
integer(4) function, public mtrandom::rng_rand (type(rng_state), intent(inout) state)
Obtain the next 32-bit integer in the pseudo-random sequence.
Parameters
state
Returns
r
References rng_rand64().
rng_rand64()
integer(i64) function, public mtrandom::rng_rand64 (type(rng_state), intent(inout) state)
Obtain the next 64-bit (orig said 32??) integer in the pseudo-random sequence.
Parameters
state
Returns
r a 64-bit integer
Remarks
variable names match those in original example
Referenced by rng_rand(), rng_rand_real1(), rng_rand_real2(), rng_rand_real3(), and random::rng_rand_real_array1d().
rng_rand_range()
integer(4) function, public mtrandom::rng_rand_range (type(rng_state), intent(inout) state, integer, intent(in) lo, integer, intent(in) hi)
Obtain a pseudorandom integer in the range [lo,hi].
Parameters
state
lo minimum value possible on output
hi minimum value possible on output
Returns
one pseudorandom integer less or equal than lo and greater or equal than hi
References rng_rand_real2().
rng_rand_real1()
real(dp) function, public mtrandom::rng_rand_real1 (type(rng_state), intent(inout) state)
Obtain a pseudorandom real number in the range [0,1],.
Parameters
state
Returns
a number greater than or equal to 0 and less than or equal to 1.
References rng_rand64().
Referenced by random::rng_rand_real_array0d().
rng_rand_real2()
real(dp) function, public mtrandom::rng_rand_real2 (type(rng_state), intent(inout) state)
Obtain a pseudorandom real number in the range [0,1)
Parameters
state
Returns
a number greater than 0 and less than or equal to 1.
References rng_rand64().
Referenced by rng_rand_range().
rng_rand_real3()
real(dp) function, public mtrandom::rng_rand_real3 (type(rng_state), intent(inout) state)
Obtain a pseudorandom real number in the range (0,1)
Parameters
state
Returns
a number greater than 0 and less than 1.
References rng_rand64().