NuMFor: csplevder Interface Reference
csplevder Interface Reference
csplev Performs a spline interpolation in a point or in a table
Public Member Functions
real(dp) function cspl_interpdev (xc, csp, m)
Interpolates the first derivative of a function.
real(dp) function, dimension(size(xnew)) cspl_interpdev_tab (xnew, csp, m)
Detailed Description
csplev Performs a spline interpolation in a point or in a table
See also
cspl_interpdev and cspl_interpdev_tab
Example:
  ! Given a CubicSpline object csp evaluate the derivative
  yder = csplevder(xnew, csp)
Member Function/Subroutine Documentation
cspl_interpdev()
real(dp) function cspl_interpdev (real(dp), intent(in) xc, class(cubicspline), intent(in) csp, integer, intent(in), optional m)
Interpolates the first derivative of a function.
Note
Before calling this function, must be called csplrep()
Parameters
[in] xc value where evaluate the interpolation
[in] csp spline coefficients
[in] m order of derivation
Returns
the interpolated value
References polynomial::polyder(), and basic::print_msg().
cspl_interpdev_tab()
real(dp) function, dimension(size(xnew)) cspl_interpdev_tab (real(dp), dimension(:), intent(in) xnew, class(cubicspline), intent(in) csp, integer, intent(in), optional m)
Parameters
[in] csp spline coefficients
[in] xnew array of x values
Returns
Interpolated values
Parameters
[in] m order of derivative
References polynomial::polyder(), basic::print_msg(), and basic::small.
The documentation for this interface was generated from the following file:
/home/fiol/Trabajos/fortran/numfor/src/interpolate/csplines.f90