NuMFor: grids Module Reference
grids Module Reference
This module provides convenience routines to create grids Description: docarrays.
Functions/Subroutines
real(dp) function, dimension(num), public linspace (start, end, num, endpoint, retstep)
real(dp) function, dimension(num), public logspace (start, end, num, endpoint, base)
Makes a grid with numbers spaced evenly on a log scale.
real(dp) function, dimension(num), public geomspace (start, end, num, endpoint)
Makes a grid with numbers spaced evenly on a log scale.
real(dp) function, dimension(num), public loglinspace (start, end, num, step, ratio)
loglinspace Computes a grid that may behave as linearly or logarithmically spaced
integer function, dimension(:), allocatable, public arange (start, end, step)
arange: Return evenly spaced integer values within a given interval
Detailed Description
This module provides convenience routines to create grids Description: docarrays.
Function/Subroutine Documentation
arange()
integer function, dimension(:), allocatable, public arange (integer, intent(in) start, integer, intent(in) end, integer, intent(in), optional step)
arange: Return evenly spaced integer values within a given interval
Values are generated within the half-open interval [start, end) (in other words, the interval including start but excluding end).
Parameters
[in] start the starting value of the interval.
[in] end the final value of the interval (not included)
[in] step Spacing between values.
Returns
A sequence of numbers spaced evenly
geomspace()
real(dp) function, dimension(num), public geomspace (real(dp), intent(in) start, real(dp), intent(in) end, integer, intent(in) num, logical, intent(in), optional endpoint)
Makes a grid with numbers spaced evenly on a log scale.
Note
: Is similar to logspace but with endpoints specified directly. Also accepts simultaneously negative start and end
Parameters
[in] start start is the starting value
[in] end end is the final value of
[in] num Number of samples to generate. Must
[in] endpoint If True, end is
Returns
A sequence of numbers spaced evenly on a log scale.
Examples:
  print '(4(f8.2,1x))', geomspace(1._dp, 1000._dp, num=4)
  ! gives:     1.00    10.00   100.00  1000.00
  print '(4(f8.2,1x))', geomspace(-1000._dp, -1._dp, num=4)
  ! gives: -1000.00  -100.00   -10.00    -1.00
References logspace().
linspace()
real(dp) function, dimension(num), public linspace (real(dp), intent(in) start, real(dp), intent(in) end, integer, intent(in) num, logical, intent(in), optional endpoint, real(dp), intent(out), optional retstep)
Parameters
[in] start The starting value of the
[in] end The end value of the sequence,
[in] num Number of samples to generate. Must
[in] endpoint If True, end is
[out] retstep If present, return
Returns
An array of uniformly spaced numbers
Examples:
  print "(5(f4.2,1x))", linspace(2._dp, 3.0_dp, num=5)
  ! Gives: 2.00 2.25 2.50 2.75 3.00
  print "(5(f4.2,1x))", linspace(2._dp, 3.0_dp, num=5, endpoint=.false.)
  ! Gives: 2.00 2.20 2.40 2.60 2.80
  print "(5(f4.2,1x))", linspace(2._dp, 3.0_dp, num=5, retstep=step)
  ! Gives: 2.00 2.25 2.50 2.75 3.00
References basic::zero.
Referenced by histograms::histogram(), and logspace().
loglinspace()
real(dp) function, dimension(num), public loglinspace (real(dp), intent(in) start, real(dp), intent(in) end, integer, intent(in) num, real(dp), intent(in), optional step, real(dp), intent(in), optional ratio)
loglinspace Computes a grid that may behave as linearly or logarithmically spaced
From package RADIAL by Salvat et al 1995 Computer Physics Communications. The grid is such that:
R(1)=0, R(NP)=RN,
A*R(I)+B*DLOG(R(I))-C= I (I > 0), with A=1.0/STEP and B=1.0/DLOG(RATIO).
Parameters
[in] start Starting value
[in] end Final value of the sequence
[in] num Number of points
[in] step Approximated step in the linear region
[in] ratio quotient between consecutive points in the logarithmic region
Returns
Array of points with the grid of dimension num
Examples:
logspace()
real(dp) function, dimension(num), public logspace (real(dp), intent(in) start, real(dp), intent(in) end, integer, intent(in) num, logical, intent(in), optional endpoint, real(dp), intent(in), optional base)
Makes a grid with numbers spaced evenly on a log scale.
In linear space, the sequence starts at base**start (base to the power of start) and ends with base**end
Parameters
[in] start base**start is the starting value of the sequence.
[in] end base**end is the final value of the sequence.
[in] num Number of samples to generate. Must be positive.
[in] endpoint If True, end is the last sample. Otherwise, it is not included. Default is True
[in] base The base of the log space. Default is 10.
Returns
A sequence of numbers spaced evenly on a log scale.
Examples:
  print '(4(f8.2,1x))', logspace(2._dp, 3.0_dp, num=4)
  ! gives:  100.00   215.44   464.16  1000.00
  print '(4(f8.2,1x))', logspace(2.0_dp, 3.0_dp, num=4, base=2.0_dp)
  ! gives:    4.00     5.04     6.35     8.00
  print '(4(f8.2,1x))', logspace(3._dp, zero, 4)
  ! gives: 1000.00   100.00    10.00     1.00
References linspace().
Referenced by geomspace().